[workspace]
members = [ "crates/bug_injection",
    "crates/hpc-core"]
resolver = "2" 

[profile.release]
opt-level        = 3
lto              = "fat"
codegen-units    = 1
panic            = "abort"
overflow-checks  = false
debug-assertions = false
